/// Flutter icons CustomIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String? _kFontPkg = null;

  static const IconData message = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_review = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recently_seen = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
